using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

using Microsoft.Extensions.Logging;
using Microsoft.Win32.TaskScheduler;

using RunAsAdminPolMan.Core.Models;
using RunAsAdminPolMan.Core.Services;

namespace RunAsAdminPolMan.Infrastructure.Services;

/// <summary>
/// Infrastructure implementation for generating elevated scheduled tasks.
/// </summary>
public class TaskSchedulerService : ITaskSchedulerService
{
    private const string TaskFolder = @"\RunAsAdminPolMan";
    private readonly ILogger<TaskSchedulerService> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="TaskSchedulerService"/> class.
    /// </summary>
    /// <param name="logger">The logger instance.</param>
    public TaskSchedulerService(ILogger<TaskSchedulerService> logger)
    {
        _logger = logger;
    }

    /// <inheritdoc/>
    public async System.Threading.Tasks.Task<Result<string>> CreateElevatedTaskAsync(AppPolicy policy, CancellationToken cancellationToken = default)
    {
        return await System.Threading.Tasks.Task.Run(() =>
        {
            if (string.IsNullOrWhiteSpace(policy.FilePath) || !File.Exists(policy.FilePath))
            {
                return Result<string>.Fail(new Error("FILE_NOT_FOUND", "The specified executable file does not exist."));
            }

            string safeProductName = string.IsNullOrWhiteSpace(policy.ProductName)
                ? Path.GetFileNameWithoutExtension(policy.FilePath)
                : string.Join("_", policy.ProductName.Split(Path.GetInvalidFileNameChars()));

            string taskName = $"{TaskFolder}\\{safeProductName}";

            try
            {
                using var ts = new TaskService();

                // Idempotency: Overwrite existing task if it exists
                var existingTask = ts.GetTask(taskName);
                if (existingTask != null)
                {
                    _logger.LogInformation("Task {TaskName} already exists. It will be overwritten.", taskName);
                }

                TaskDefinition td = ts.NewTask();
                td.RegistrationInfo.Description = $"UAC Bypass Task for {safeProductName} generated by RunAsAdmin Policy Manager.";

                // Run with highest privileges (UAC Bypass core mechanism)
                td.Principal.RunLevel = TaskRunLevel.Highest;
                td.Principal.LogonType = TaskLogonType.InteractiveToken;

                td.Actions.Add(new ExecAction(policy.FilePath, string.IsNullOrWhiteSpace(policy.Arguments) ? null : policy.Arguments, Path.GetDirectoryName(policy.FilePath)));

                // Disable power restrictions (run on battery)
                td.Settings.DisallowStartIfOnBatteries = false;
                td.Settings.StopIfGoingOnBatteries = false;
                td.Settings.ExecutionTimeLimit = TimeSpan.Zero;

                _logger.LogDebug("Registering Highest Privilege Task: {TaskName}", taskName);
                ts.RootFolder.RegisterTaskDefinition(taskName, td, TaskCreation.CreateOrUpdate, null, null, TaskLogonType.InteractiveToken);

                return Result<string>.Success(taskName);
            }
            catch (UnauthorizedAccessException ex)
            {
                _logger.LogWarning(ex, "Unauthorized access while attempting to create scheduled task.");
                return Result<string>.Fail(new Error("UNAUTHORIZED", "Administrator privileges are required to create scheduled tasks."));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to create scheduled task {TaskName}.", taskName);
                return Result<string>.Fail(new Error("TASK_SCHEDULER_ERROR", "An unexpected error occurred while communicating with the Windows Task Scheduler."));
            }
        }, cancellationToken);
    }
}