<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>runassu</AssemblyName>
    <!-- Infrastructure uses System.Drawing.Common, so we must enable WindowsForms -->
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RunAsAdminPolMan.Core\RunAsAdminPolMan.Core.csproj" />
    <ProjectReference Include="..\RunAsAdminPolMan.Infrastructure\RunAsAdminPolMan.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="run-as-su.cmd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RunAsAdminPolMan.Bootstrapper\RunAsAdminPolMan.Bootstrapper.csproj" ReferenceOutputAssembly="false" OutputItemType="Content" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
